Must create retry policy for JavaScript.
INFO: POST DETECTED: http://senat.ro/FisaSenator.aspx?ParlamentarID=236250d7-10f3-4fd9-b9c7-8916a712b4c1
Nov 23, 2015 6:51:28 AM com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl runSingleJob
SEVERE: Job run failed with unexpected RuntimeException: Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Transaction (Process ID 124) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (http://senat.ro/ScriptResource.axd?d=sNpNcbuc8ut2lav4Ag2coBKROlu6pYys7hasGxyv9qfiOkZegBIHmaGL1Cc2t85ZbXqSDPRzmm1KqB3hdYzHK313RVd74Ct6bjMmuQzBYHxh5ceZigv910IDhGcIneVkmi68Dc0Wl_t_pLsD3grOxA2&t=ffffffff9fba30f1#940)
======= EXCEPTION START ========
Exception class=[net.sourceforge.htmlunit.corejs.javascript.JavaScriptException]
com.gargoylesoftware.htmlunit.ScriptException: Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Transaction (Process ID 124) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (http://senat.ro/ScriptResource.axd?d=sNpNcbuc8ut2lav4Ag2coBKROlu6pYys7hasGxyv9qfiOkZegBIHmaGL1Cc2t85ZbXqSDPRzmm1KqB3hdYzHK313RVd74Ct6bjMmuQzBYHxh5ceZigv910IDhGcIneVkmi68Dc0Wl_t_pLsD3grOxA2&t=ffffffff9fba30f1#940)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:954)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:885)
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.setState(XMLHttpRequest.java:221)
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.doSend(XMLHttpRequest.java:809)
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest.access$000(XMLHttpRequest.java:107)
	at com.gargoylesoftware.htmlunit.javascript.host.xml.XMLHttpRequest$1.run(XMLHttpRequest.java:664)
	at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:628)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
	at com.gargoylesoftware.htmlunit.javascript.background.JavascriptXMLHttpRequestJob.run(JavascriptXMLHttpRequestJob.java:36)
	at com.gargoylesoftware.htmlunit.javascript.background.JavaScriptJobManagerImpl.runSingleJob(JavaScriptJobManagerImpl.java:427)
	at com.gargoylesoftware.htmlunit.javascript.background.DefaultJavaScriptExecutor.run(DefaultJavaScriptExecutor.java:167)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Transaction (Process ID 124) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction. (http://senat.ro/ScriptResource.axd?d=sNpNcbuc8ut2lav4Ag2coBKROlu6pYys7hasGxyv9qfiOkZegBIHmaGL1Cc2t85ZbXqSDPRzmm1KqB3hdYzHK313RVd74Ct6bjMmuQzBYHxh5ceZigv910IDhGcIneVkmi68Dc0Wl_t_pLsD3grOxA2&t=ffffffff9fba30f1#940)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1006)
	at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
	at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
	at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:411)
	at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
	at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3286)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$4.doRun(JavaScriptEngine.java:878)
	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:939)
	... 13 more
JavaScriptException value = Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Transaction (Process ID 124) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
== CALLING JAVASCRIPT ==
  function () {
      if (_this._xmlHttpRequest.readyState === 4) {
          try {
              if (typeof (_this._xmlHttpRequest.status) === "undefined") {
                  return;
              }
          }
          catch (ex) {
              return;
          }
          _this._clearTimer();
          _this._responseAvailable = true;
          _this._webRequest.completed(Sys.EventArgs.Empty);
          if (_this._xmlHttpRequest) {
              _this._xmlHttpRequest.onreadystatechange = Function.emptyMethod;
              _this._xmlHttpRequest = null;
          }
      }
  }
======= EXCEPTION END ========